// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AntLayout: typeof import('./src/components/AntLayout.vue')['default']
    HttpJobDelete: typeof import('./src/components/HttpJobDelete.vue')['default']
    HttpJobForm: typeof import('./src/components/HttpJobForm.vue')['default']
    HttpJobGroupList: typeof import('./src/components/HttpJobGroupList.vue')['default']
    HttpJobList: typeof import('./src/components/HttpJobList.vue')['default']
    HttpJobLogList: typeof import('./src/components/HttpJobLogList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
