CREATE TABLE HTTP_JOB_EXECUTION
(
    INSTANCE_ID BIGINT       NOT NULL AUTO_INCREMENT,
    START_TIME  datetime     NULL,
    END_TIME    datetime     NULL,
    STATUS_CODE INT          NULL,
    RESPONSE    MEDIUMTEXT   NULL,
    JOB_NAME    VARCHAR(255) NULL,
    JOB_GROUP   VARCHAR(255) NULL,
    CONSTRAINT PK_HTTP_JOB_EXECUTION PRIMARY KEY (INSTANCE_ID)
) ENGINE = InnoDB;

CREATE INDEX IDX_HTTP_JOB_ID
    on HTTP_JOB_EXECUTION (JOB_NAME, JOB_GROUP);