spring:
  datasource:
    webcron:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webcron
      username: root
      password: test
      hikari:
        pool-name: mysql-webcron-hikariCP
        connection-timeout: 30000
        max-lifetime: 30000
        maximum-pool-size: 2
        leak-detection-threshold: 1000